### ISSUE TITLE
confused on how to create and destroy repr_c::Vec 

### ISSUE THREAD

**Issue by TheButlah** [getditto/safer_ffi#109]
I used `repr_c::Vec<T>` in my FFI, but now I'm faced with a function that accepts a new `repr_c::Vec` as input. I don't see in the generated bindings any way to free or create a `repr_c::Vec`. Is that functionality unimplemented? Is there any documentation for this?

I know I can wrap `drop()` in a `free_my_t()` function, but that still doesn't address how to actually push items into a `repr_c::Vec`

**Comment by danielhenrymantilla** [comment]
Continuing over https://github.com/getditto/safer_ffi/discussions/112
