### ISSUE TITLE
`#[ffi_export]` doesn't work with `mut` keyword in parameters

### ISSUE THREAD

**Issue by TheButlah** [getditto/safer_ffi#110]
This code:
```rust
#[ffi_export]
pub fn f(mut v: repr_c::Vec<u8>) {
    // let mut v = v;
    v.with_rust_mut(|v| *v = Vec::new());
}
```
Fails with this error:
![image](https://user-images.githubusercontent.com/6969415/169177773-6e6d261e-8f9b-4d02-9d9b-8154b4119e3c.png)

This error goes away when uncommenting the line and removing `mut` from the parameter

**Comment by danielhenrymantilla** [comment]
Fixed as of https://crates.io/crates/safer-ffi/0.0.10
