### ISSUE TITLE
Pushing to a safer-ffi Vec does not change `len` or `cap`

### ISSUE THREAD

**Issue by TheButlah** [getditto/safer_ffi#118]
I have the following binding code:

```rust
#[ffi_export]
pub fn my_push(vec: &mut ::safer_ffi::vec::Vec<u8>, item: ::safer_ffi::boxed::Box<u8>) {
    let item: u8 = *item.into();
    vec.with_rust_mut(|vec| vec.push(item))
}
```

I pass a `Vec_u8_t*` to the function on the C side (this is actually being done in C# where I have my struct and take a reference to it and cast that to an `IntPtr` and pass that). It doesn't appear as though the `len` or `cap` fields actually change however.

**Comment by danielhenrymantilla** [comment]
This is very worrysome indeed 💯, but since you mention C#, I suspect it may have to do with how it is marshalled. Soon `safer-ffi` will make its experimental support of C# headers official, which are designed to minimize the marshalling interference from C#'s runtime.

To confirm my hypothesis, could you share how you've wrapped that `Vec<u8>`?

**Comment by TheButlah** [comment]
we are using cppsharp to do the generation. It creates some PInvoke DLLImports, and also some higher level wrappers on top of those. The wrappers are insufficient for our use because they don't seem to capture ownership semantics, so we are using the pinvoke statements that cppsharp generates directly.

The original code example I gave is a simplification, here is the real one:

```c#
[SuppressUnmanagedCodeSecurity, DllImport("tp_client", EntryPoint = "tp_client__contract__properties__channels__RVec_KeyframeU32__push", CallingConvention = __CallingConvention.Cdecl)]
            internal static extern void TpClientContractPropertiesChannelsRVecKeyframeU32Push(__IntPtr vec, __IntPtr item);
```

```rust
#[::safer_ffi::ffi_export]
pub fn tp_client__contract__properties__channels__RVec_KeyframeU32__push(vec: &mut ::safer_ffi::vec::Vec<Keyframe_U32>, item: ::safer_ffi::boxed::Box<$t>) {
    let item: $t = *item.into();
    vec.with_rust_mut(|vec| vec.push(item))
}
```

This is a partial expansion of some cursed macros that handle name mangling and monomorphization of our types 😅

**Comment by danielhenrymantilla** [comment]
> `            var shared = this.Inner.Value;`

so this is the copy I was suspecting could be happening: you'll need to `this.Inner.Value = shared;` after the FFI call to make sure the change is propagated to `this.Inner` and thus `this`

**Comment by TheButlah** [comment]
Thank you! That was indeed the problem. Sorry for the trouble, closing as resolved
