### ISSUE TITLE
safer_ffi may randomly generate empty headers

### ISSUE THREAD

**Issue by pan93412** [getditto/safer_ffi#131]
## Abstract

Sometimes `safer_ffi` generates an empty headers like the following screenshot on my Mac:

![截圖 2022-08-13 下午7 44 03](https://user-images.githubusercontent.com/28441561/184492658-0f03a3a4-2512-4d56-85bb-414247263924.png)

After setting up the breakpoint and debugging, I found that `inventory::iter` ended up really fast – like nothing registered:

<img width="992" alt="image" src="https://user-images.githubusercontent.com/28441561/184492989-c8a68556-6fea-47e0-b092-f04e3dd02317.png">

<img width="1264" alt="image" src="https://user-images.githubusercontent.com/28441561/184493007-b96f7e0e-7d8e-444e-b7d7-92dd79d481fb.png">

As it works on my another Ubuntu machine, I guess it is related to https://github.com/dtolnay/inventory/issues/9? [I tried to upgrade `Inventory` to 3.0.1](https://github.com/pan93412/safer_ffi/tree/c07b890b73b3d193b514d96544e3fd79f87a247b); however, the compilation failed:

![截圖 2022-08-13 下午7 57 16](https://user-images.githubusercontent.com/28441561/184493060-35b0cf7d-4531-4d51-bede-8cc60cd17568.png)

Not really sure how to fix it. 

## Expected Behavior (on my Ubuntu machine)

![截圖 2022-08-13 下午7 59 25](https://user-images.githubusercontent.com/28441561/184493128-511f082e-b2c1-4a8b-9751-38ec01ef9536.png)

## Metadata

- **rustc version**: rustc 1.65.0-nightly (20ffea693 2022-08-11)
- **cargo version** cargo 1.65.0-nightly (ce40690a5 2022-08-09)
- **OS version** macOS Monterey 12.5 (ARM64)
- **Reproducible Repo**: https://github.com/pan93412/libstock-ffi/tree/e87b04cf6e1bd9394db656315f1dbd2975418c95

**Comment by danielhenrymantilla** [comment]
Thanks for the very detailed, link-backed, and extended report 🙏

**Comment by danielhenrymantilla** [comment]
\[Continuing from #132\]

___

> Maybe we should report it to the upstream? Not sure about it.

Yeah, maybe; although if we do that we'd need to really reduce the example, right now there is too much `safer-ffi` glue to report it to inventory.

Until then, you could try to work around the limitation, in and of itself, by making more `mod`ules `pub`, I guess:

  - _e.g._, using https://docs.rs/visibility

    you could try to slap `#[cfg_attr(feature = "headers", visibility::make(pub)]` on your `mod`ules and see how it goes 🤷

**Comment by pan93412** [comment]
<img width="724" alt="image" src="https://user-images.githubusercontent.com/28441561/185173486-e2bb8074-9e93-40f3-b09d-1dac477656d7.png">

<img width="828" alt="image" src="https://user-images.githubusercontent.com/28441561/185173685-98311569-e6da-4328-9d80-c5e91b509f8d.png">

It seems not working. However, the symbols exported from bin `gen-headers` are less those from the static library file – including “last_error_length” and something else:

- lib: [symbols.libwmjtyd-libstock.txt](https://github.com/getditto/safer_ffi/files/9363999/symbols.libwmjtyd-libstock.txt)
- bin: [symbols.gen-header.txt](https://github.com/getditto/safer_ffi/files/9363998/symbols.gen-header.txt)

Although my Ubuntu machine also did not export them, maybe we can find some clues inside these symbol tables?

- lib: [symbols.lib.ubuntu.txt](https://github.com/getditto/safer_ffi/files/9364080/symbols.lib.ubuntu.txt)
- bin: [symbols.gen-header.ubuntu.txt](https://github.com/getditto/safer_ffi/files/9364083/symbols.gen-header.ubuntu.txt)

**Comment by danielhenrymantilla** [comment]
https://github.com/dtolnay/linkme/issues/31#issuecomment-1193271214 seems to suggest the inventory bug is still around 😔

**Comment by pan93412** [comment]
@danielhenrymantilla I resolved it with a weird way – I switched my linker to mold (for macOS), and it seems work now…? 😂

<img width="1440" alt="Switch zld to mold, and header generation works now" src="https://user-images.githubusercontent.com/28441561/187145891-8881876b-df63-46d9-9197-2b20e94d1b35.png">

I'll continue observing this issue, but at least it works at this moment 😄

**Comment by danielhenrymantilla** [comment]
Great news! Having a workaround for this ought to be quite useful, even if it's not an actual solution (_e.g._, somebody may need to use something different than mold for other reasons on their project 😅).
