### ISSUE TITLE
Generate doc comments for structs

### ISSUE THREAD

**Issue by jsantell** [getditto/safer_ffi#151]
When generating headers, doc comments for structs and enums are not generated in the headers. We'd like to support Doxygen style docs e.g. with `@class` for structs and `@memberof` bindings for functions, to both annotate our structs, and organize our functions. Is this currently supported (I see that enums and structs have `emit_docs()` in their implementation) or any guidance/suggestions on where this can be implemented?

Example:

```rust
#[derive_ReprC]
#[ReprC::opaque]
/// This is a foo object.
/// @class foo_t
pub struct Foo {}

#[ffi_export]
/// Creates a new foo_t.
/// @memberof foo_t
pub fn new_foo() -> Option<repr_c::Box<Foo>> { .. }
```

generates something like:

```c
typedef struct Foo Foo_t;

/** \brief
 *  Creates a new foo_t.
 * @memberof foo_t
 */
Foo_t* new_foo();
```

Thanks!

**Comment by danielhenrymantilla** [comment]
So, this is the code that handles C header generation for opaque types:

https://github.com/getditto/safer_ffi/blob/bb55971c4287827bb54e5892f7f02523fb951fb7/src/headers/languages/c.rs#L144-L161

And for functions:

https://github.com/getditto/safer_ffi/blob/bb55971c4287827bb54e5892f7f02523fb951fb7/src/headers/languages/c.rs#L163-L174

I think the difficulty here would be for `@memberof` to be auto-generated; but if hand-annotated as with your Rust code example then it should work; if it doesn't then I might have a bug with the macro layer that calls into these helper functions

**Comment by danielhenrymantilla** [comment]
> Any timelines on landing non-RC 0.1.0?

It should be rather soon (~2 weeks), I just need to take the time to polish outstanding oversights I may have missed, once I find the time for that: https://github.com/getditto/safer_ffi/pull/157
