### ISSUE TITLE
scopeguard breaking no_std build

### ISSUE THREAD

**Issue by unovongalixor** [getditto/safer_ffi#168]
I'm trying to use safer_ffi to handle ffi stuff on an embedded device. i'm building my no_std project for --target thumbv7em-none-eabi, and i've included safer_ffi in cargo.toml with default-features = false, yet when i try to build, i get errors about missing STD from scopeguard. i checked and it seems scopeguard should work without std as well if default features are disabled. Is it possible this feature isn't getting forwarded to the dependencies?

`Compiling scopeguard v1.1.0 error[E0463]: can't find crate for std`

**Comment by unovongalixor** [comment]
`   Compiling scopeguard v1.1.0
error[E0463]: can't find crate for `std`
  |
  = note: the `thumbv7em-none-eabi` target may not support the standard library
  = note: `std` is required by `scopeguard` because it does not declare `#![no_std]`
  = help: consider building the standard library from source with `cargo build -Zbuild-std`
`

**Comment by danielhenrymantilla** [comment]
Thanks for the report! This should have been fixed in the `v0.1.1` I've just released 🙂

**Comment by unovongalixor** [comment]
upgraded to 1.1.0, now I get the following error re: libc

for the sake of clarity i am writing a no_std, no_main staticlib

![image](https://github.com/getditto/safer_ffi/assets/9163601/47ffa4c8-2f9d-47f1-a6ee-1a1f07fe8841)

**Comment by danielhenrymantilla** [comment]
I'll look at this and fix it tomorrow (in 14h-ish); are you using wasm? In theory [`libc` should be pulled in for non-`wasm32-unknown-unknown` targets](https://github.com/getditto/safer_ffi/blob/140dd8f4f96a63788f344503d4c0cc66dd8d4ea7/Cargo.toml#L166-L168) 🤔

**Comment by unovongalixor** [comment]
Nope, I'm building for thumbv7em-none-eabi, Cortex M4 bare metal, no_std, no_main. If you can point me to where it's being included I maybe I can put together a pr

**Comment by unovongalixor** [comment]
if you look [here](https://rust-lang.github.io/libc/#platform-specific-documentation) libc doesn't support my target. curious to know how you think i can approach this, as I really want to use safer_ffi for bare metal static libraries.

**Comment by unovongalixor** [comment]
there's an [old commit](https://github.com/getditto/safer_ffi/pull/121/files#diff-59d6931356435884540e9174cf6a8c3de8350544362f83f113c10827da580b5cR30) that fixes this issue for wasm (got to it from [this issue](https://github.com/getditto/safer_ffi/issues/120)), i believe the thumb targets need the same handling. if you use size_t like with wasm, it will work here too. basically any platform without libc support will need this handling.

**Comment by danielhenrymantilla** [comment]
@unovongalixor #170 should be fixing this, you can test it early with a `patch` directive:

```toml
[patch.crates-io.safer-ffi]
git = "https://github.com/getditto/safer_ffi.git"
rev = "7d0770d7936c5a732a67bd59f447eb1655011622"
```
