### ISSUE TITLE
Trivial example requires `python-headers` feature to build

### ISSUE THREAD

**Issue by cdata** [getditto/safer_ffi#175]
Hello, [one of my projects](https://github.com/subconsciousnetwork/noosphere) makes extensive use of `safer-ffi`. Thank you so much for making it available for general consumption; we love it.

Recently I compiled against `v0.1.2` of the `safer-ffi` package and noticed a regression compared to the version we had been using (`v0.1.0-rc.1`). Specifically, we were seeing this compiler error on a number of our exports:

```
error[E0425]: cannot find value `Python` in module `languages`
 --> src/main.rs:3:1
  |
3 | #[ffi_export]
  | ^^^^^^^^^^^^^ not found in `languages`
  |
  = note: this error originates in the attribute macro `ffi_export` (in Nightly builds, run with -Z macro-backtrace for more info)
 ```
 
Poking around, I noticed that the codegen was indeed referencing a variant that was only available in `safer-ffi` conditionally. Adding the `python-headers` feature flag to `safer-ffi` "fixed" the problem by making the variant available.

I have made a reduced test case of this problem here: https://github.com/cdata/safer-ffi-fail-case

The test case is currently in a broken state. If you add the `python-headers` feature to the `safer-ffi` dependency, you will see that the package can build.

We do intend to write Python bindings eventually so this isn't a blocker for us or anything, but it smelled like unintended behavior so I figured I should report it.

**Comment by danielhenrymantilla** [comment]
Thanks for the report! Will look into this in the following days; although I'm pretty busy atm so the fix may take until Monday. Is downgrading to the previous version an option for you to stall in the meantime, or is this urgent?

**Comment by cdata** [comment]
It's not urgent at all; we are not blocked by this issue AFAICT. I'll let you know if I realize we are :sweat_smile:
