### ISSUE TITLE
Compatibility with C++ vector

### ISSUE THREAD

**Issue by EricLBuehler** [getditto/safer_ffi#196]
Hello!

This looks like a really cool crate! I want to use my Vec with a C++ API (that I cannot change) that uses the std::vector type. Is this possible to do with this crate?

**Comment by danielhenrymantilla** [comment]
I'll try to look into that 🙂 In the meantime, you may be interested in the `cxx` framework which specializes on C++ interop: https://cxx.rs/

**Comment by EricLBuehler** [comment]
Ok, thanks.
