### ISSUE TITLE
Missing libraries in README.md C compilation example

### ISSUE THREAD

**Issue by wahn** [getditto/safer_ffi#20]
On my system (Ubuntu Linux) I had to add **two** more **libraries** (`-lpthread -ldl`) in the compilation/linking line for `main.c`:

``` shell
$ cc main.c -o main -L target/debug -ltest_ffi -lpthread -ldl
```

Maybe worth mentioning this in the `README.md` file ...

**Comment by danielhenrymantilla** [comment]
Wops, that was an oversight indeed, thanks for reporting it!
