### ISSUE TITLE
Using #[derive_reprC] with derive attributes

### ISSUE THREAD

**Issue by clegaard** [getditto/safer_ffi#28]
Is there a way to use #[derive_reprC] with other derive attributes for enums?

When trying to compile:
``` rust
#[derive_ReprC]
#[derive(PartialEq)]
#[repr(i32)]
pub enum Fmi2Status {
    Fmi2OK,
    Fmi2Warning,
    Fmi2Discard,
    Fmi2Error,
    Fmi2Fatal,
    Fmi2Pending,
}
```

I get:
```
63 | #[derive(PartialEq)]
   |   ^^^^^^ no rules expected this token in macro call
```

**Comment by danielhenrymantilla** [comment]
This situation will be improved soon when I move to total proc-macro implementations. In the meantime, moving the `#[repr(...)]` _before_ other attributes (except for `#[derive_ReprC]`) ought to work 🙂

**Comment by clegaard** [comment]
Like so?

``` rust
#[repr(i32)]
#[derive(PartialEq)]
#[derive_ReprC]
pub enum Fmi2Status {
    Fmi2OK,
    Fmi2Warning,
    Fmi2Discard,
    Fmi2Error,
    Fmi2Fatal,
    Fmi2Pending,
}
```
This also came to my mind, but I get the error:

```
error: macro attributes must be placed before `#[derive]`
  --> src\lib.rs:64:1
   |
64 | #[derive_ReprC]
   | ^^^^^^^^^^^^^^^
```

By the way, great work on the module :)

**Comment by danielhenrymantilla** [comment]
Almost there 😄  :

```rust
#[derive_ReprC] // needs to be before the derives
#[repr(i32)] // needs to be the first attribute derive_ReprC sees (until it is fixed)
#[derive(…)]
enum …
```

**Comment by clegaard** [comment]
Thank you that solved the issue, I could have sworn I already tried this 😆

**Comment by waynexia** [comment]
How about making `ReprC` trait derive-able like [this](https://doc.rust-lang.org/reference/procedural-macros.html#derive-macros)?

**Comment by danielhenrymantilla** [comment]
@waynexia Yeah, that might probably be doable once we perform the shift to fully procedural implementations; the crate started using `macro_rules!` macros, as in:

```rust
#[derive_ReprC]
struct Foo { x: i32 }
// becomes:
ReprC! {
    struct Foo { x: i32 }
}
```

and the latter, since it was supposed to also be a standalone-usable public macro, it needs to re-emit the given definition, which contradicts a `derive` implementation (which mustn't re-emit the given input, lest it appear twice, conflicting with one another).

Your suggestion would thus be covered by:

  - https://github.com/getditto/safer_ffi/issues/46

    The idea there is that there could be two approaches:

    ```rust
    #[derive(ReprC)]
    #[repr(C)] // <- error if missing repr
    struct …
    ```

    or:

    ```rust
    #[safer_ffi::repr(C)] // <- the attribute attaches its own repr
    struct …
    ```

      - <sub><sup>The latter still "suffers" from the ordering issues mentioned in this very issue, but would be the more flexible approach, by allowing the attribute to attach `repr`, or other such attributes (should there appear more in the future), in a rather API-encapsulated way. That is, it would be the more future-proof approach. But we'll see what we end uo going for</sup></sub>

**Comment by waynexia** [comment]
Thanks for the clear explanation @danielhenrymantilla ! 

> it needs to re-emit the given definition, which contradicts a derive implementation

This is a bit annoying. `ReprC` is not that similar with other traits that are easy to derive - it needs to modify the definition of struct to add repr annotation. Proc macro might be a better way in this regard.
