### ISSUE TITLE
ffi_export macro does not support "where clause"

### ISSUE THREAD

**Issue by DBLouis** [getditto/safer_ffi#45]
The `ffi_export` macro does not seem to support `where` clause with lifetime bounds, like this:

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=f3c8563987bccc4b85d5c7b34298c49a

**Comment by danielhenrymantilla** [comment]
This may be a limitation from the current `macro_rules!`-based implementation of the attribute. A revamp of `safer-ffi` to promote these macros to full-featured proc-macros will solve this, and that revamp ought to be happening within the following weeks. Stay tuned!
