### ISSUE TITLE
how to let ReprC work with thrid party crate struct ? 

### ISSUE THREAD

**Issue by gcxfd** [getditto/safer_ffi#68]
I want to use safer_ffi with blake3 Hasher, but error as below
```
the trait `ReprC` is not implemented for `blake3::Hasher`
```
![image](https://user-images.githubusercontent.com/69608605/119809986-31c44a00-bf18-11eb-89ee-8a11918e7799.png)

**Comment by danielhenrymantilla** [comment]
For those cases you have to use [the opaque object pattern](https://getditto.github.io/safer_ffi/derive-reprc/struct.html#opaque-types-forward-declarations) (with a newtype to avoid coherence issues):

```rust
#[derive_ReprC]
#[ReprC::opaque]
pub struct Hasher(pub ::blake3::Hasher);

// For convenience (you can use a helper crate to define newtype structs):
impl Hasher {
    pub fn new() -> Self { Self(::blake3::Hasher::new()) }
}
impl ::core::ops::Deref for Hasher { … }
impl ::core::ops::DerefMut for Hasher { … }

#[ffi_export]
pub fn hasher_new() -> repr_c::Box<Hasher> {
    repr_c::Box::new(Hasher::new())
}
```

**Comment by gcxfd** [comment]
thanks , I wrote a blake3 for dart base on rust blake3 
https://github.com/rmw-dart/blake3.rust/blob/master/src/lib.rs
https://github.com/rmw-dart/blake3.rust/blob/master/lib/blake3.dart
