### ISSUE TITLE
Problem: Hard to bounce between Guide, Rust Gen Docs, and Github Repo

### ISSUE THREAD

**Issue by mbalex99** [getditto/safer_ffi#9]
# Problem

It is hard to bounce between Guide, Rust Gen Docs, and Github Repo. 

# Solution

- [ ] Add GitHub Repo link in the guide sidebar
- [ ] Add Rust Generated Docs in guide sidebar
- [ ] Add GitHub Repo link in Rust Generated Docs Link
- [ ] Add Guide link in Rust Generated Docs Link

More links the better, if you know of some link that we should add, just go ahead and add it!

**Comment by danielhenrymantilla** [comment]
I have added changes to #7 that fix this. Preview:

![image](https://user-images.githubusercontent.com/9920355/84142411-08838300-aa55-11ea-9aab-538b48d000ae.png)

<img width="1221" alt="Screenshot 2020-06-09 at 13 37 28" src="https://user-images.githubusercontent.com/9920355/84143167-65cc0400-aa56-11ea-94f7-9d8e9b015923.png">
