### ISSUE TITLE
Export Enum & Constant which are not used by a function call

### ISSUE THREAD

**Issue by dignifiedquire** [getditto/safer_ffi#96]
I have some constants and enums that I would like in the C-headers, but they are not actually used by and `ffi_export`ed function, so they don't end up showing up at the moment. Any chance  this could be added?

**Comment by danielhenrymantilla** [comment]
Yes, totally: I'm currently working on revamping some things and improving rough edges, and this was kind of on my radar, but thanks to this issue I won't forget about it 🙂 

  - (I think I'll make it so a type definition can be `#[ffi_export]`-ed itself)

**Comment by dignifiedquire** [comment]
awesome, thank you
